--- 
  bridgePath: ../bridges/MockBridge
  connectorsPath: ../../config/connectors.json
  stage: "local"
  provider: "http://localhost:8545"
  seed: "filter march urge naive sauce distance under copy payment slow just warm"
  gasPrice: 2
